#endroid_qr_code:
#    writer: 'png'
#    size: 300
#    margin: 10
#    error_correction_level: 'low'
#    validate_result: false
endroid_qr_code:
    writer: 'svg'
    size: 300
    margin: 10
    foreground_color: { r: 0, g: 0, b: 0 }
    background_color: { r: 255, g: 255, b: 255 }
    error_correction_level: low # low, medium, quartile or high
    encoding: UTF-8
    logo_width: 150
    logo_height: 200
    validate_result: false # checks if the result is readable
    writer_options:
        exclude_xml_declaration: true