lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
    pass_phrase:      '2e756afe5405ec471c3dca12d8492d9e' # required for token creation, usage of an environment variable is recommended
    token_ttl:        3600