<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200702095122 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE address CHANGE ville_id ville_id INT DEFAULT NULL, CHANGE num_rue num_rue VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE carnet_vaccination CHANGE intervation_vaccination_id intervation_vaccination_id INT DEFAULT NULL, CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE vaccin_id vaccin_id INT DEFAULT NULL, CHANGE etat etat TINYINT(1) DEFAULT NULL, CHANGE date_prise_initiale date_prise_initiale DATETIME DEFAULT NULL, CHANGE rappel_vaccin rappel_vaccin VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE centre_health CHANGE centre_city_id centre_city_id INT DEFAULT NULL, CHANGE centre_type_id centre_type_id INT DEFAULT NULL, CHANGE address_id address_id INT DEFAULT NULL, CHANGE city_id city_id INT DEFAULT NULL, CHANGE centre_referent centre_referent VARCHAR(255) DEFAULT NULL, CHANGE telephone telephone INT DEFAULT NULL, CHANGE responsable_centre responsable_centre VARCHAR(255) DEFAULT NULL, CHANGE num_rue num_rue VARCHAR(255) DEFAULT NULL, CHANGE quartier quartier VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE city CHANGE region_id region_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE family CHANGE patient_child_id patient_child_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE group_family CHANGE designation designation VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE intervation_consultation CHANGE ordo_consulataion_id ordo_consulataion_id INT DEFAULT NULL, CHANGE intervation_medicale_id intervation_medicale_id INT DEFAULT NULL, CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE praticien_prescripteur_id praticien_prescripteur_id INT DEFAULT NULL, CHANGE praticien_consultant_id praticien_consultant_id INT DEFAULT NULL, CHANGE date_consultation date_consultation DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE intervation_medicale CHANGE praticien_id praticien_id INT DEFAULT NULL, CHANGE nature_intervation nature_intervation VARCHAR(255) DEFAULT NULL, CHANGE lieu_intervation lieu_intervation VARCHAR(255) DEFAULT NULL, CHANGE id_sante_patient id_sante_patient VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE intervention_vaccination CHANGE vaccin_id vaccin_id INT DEFAULT NULL, CHANGE praticien_prescripteur_id praticien_prescripteur_id INT DEFAULT NULL, CHANGE praticien_executant_id praticien_executant_id INT DEFAULT NULL, CHANGE intervation_medicale_id intervation_medicale_id INT DEFAULT NULL, CHANGE ordo_vaccination_id ordo_vaccination_id INT DEFAULT NULL, CHANGE status_vaccin status_vaccin VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE ordo_consultation CHANGE ordonnance_id ordonnance_id INT DEFAULT NULL, CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE reference_praticient_executant reference_praticient_executant VARCHAR(255) NOT NULL, CHANGE type_praticien type_praticien VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE ordo_medicaments CHANGE ordonnance_id ordonnance_id INT DEFAULT NULL, CHANGE patient_id patient_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ordo_vaccination ADD status_vaccin VARCHAR(10) NOT NULL, CHANGE vaccin_id vaccin_id INT DEFAULT NULL, CHANGE ordonnance_id ordonnance_id INT DEFAULT NULL, CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE reference_praticien_executant_id reference_praticien_executant_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ordonnace CHANGE praticien_id praticien_id INT DEFAULT NULL, CHANGE medecin_traitant_id medecin_traitant_id INT DEFAULT NULL, CHANGE date_prescription date_prescription DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE patient CHANGE type_patient_id type_patient_id INT DEFAULT NULL, CHANGE address_id address_id INT DEFAULT NULL, CHANGE address_on_born_id address_on_born_id INT DEFAULT NULL, CHANGE last_name last_name VARCHAR(50) DEFAULT NULL, CHANGE sexe sexe VARCHAR(255) DEFAULT NULL, CHANGE father_name father_name VARCHAR(255) DEFAULT NULL, CHANGE mother_name mother_name VARCHAR(255) DEFAULT NULL, CHANGE etat etat TINYINT(1) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE is_enceinte is_enceinte TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE patient_carnet_vaccination CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE carnet_vaccination_id carnet_vaccination_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patient_intervation_consultation CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE intervention_consultation_id intervention_consultation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patient_ordo_consultation CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE ordo_consultation_id ordo_consultation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patient_ordo_medicaments CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE ordo_medicaments_id ordo_medicaments_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patient_ordo_vaccination CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE ordo_vaccination_id ordo_vaccination_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patient_vaccin CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE vaccin_id vaccin_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE praticien CHANGE user_id user_id INT DEFAULT NULL, CHANGE address_id address_id INT DEFAULT NULL, CHANGE last_name last_name VARCHAR(255) DEFAULT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE phone_professional phone_professional VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE etat etat TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE praticien_specialite CHANGE praticien_id praticien_id INT DEFAULT NULL, CHANGE specialite_id specialite_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE specialite CHANGE note_specialite note_specialite VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE user CHANGE email email VARCHAR(180) DEFAULT NULL, CHANGE roles roles JSON NOT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE date_naissance date_naissance DATETIME DEFAULT NULL, CHANGE lieu_naissance lieu_naissance VARCHAR(255) DEFAULT NULL, CHANGE address address VARCHAR(255) DEFAULT NULL, CHANGE activator_id activator_id VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE vaccin CHANGE type_vaccin_id type_vaccin_id INT DEFAULT NULL, CHANGE vaccin_description vaccin_description VARCHAR(255) DEFAULT NULL, CHANGE etat etat TINYINT(1) DEFAULT NULL, CHANGE date_prise_initiale date_prise_initiale VARCHAR(255) DEFAULT NULL, CHANGE rappel1 rappel1 VARCHAR(255) DEFAULT NULL, CHANGE rappel2 rappel2 VARCHAR(255) DEFAULT NULL, CHANGE rappel3 rappel3 VARCHAR(255) DEFAULT NULL, CHANGE rappel4 rappel4 VARCHAR(255) DEFAULT NULL, CHANGE rappel5 rappel5 VARCHAR(255) DEFAULT NULL, CHANGE rappel6 rappel6 VARCHAR(255) DEFAULT NULL, CHANGE rappel7 rappel7 VARCHAR(255) DEFAULT NULL, CHANGE rappel8 rappel8 VARCHAR(255) DEFAULT NULL, CHANGE rappel9 rappel9 VARCHAR(255) DEFAULT NULL, CHANGE rappel10 rappel10 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE vaccin_centre_health CHANGE centre_health_id centre_health_id INT DEFAULT NULL, CHANGE vaccin_id vaccin_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vaccin_praticien CHANGE praticien_id praticien_id INT DEFAULT NULL, CHANGE vaccin_id vaccin_id INT DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE address CHANGE ville_id ville_id INT DEFAULT NULL, CHANGE num_rue num_rue VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE carnet_vaccination CHANGE intervation_vaccination_id intervation_vaccination_id INT DEFAULT NULL, CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE vaccin_id vaccin_id INT DEFAULT NULL, CHANGE etat etat TINYINT(1) DEFAULT \'NULL\', CHANGE date_prise_initiale date_prise_initiale DATETIME DEFAULT \'NULL\', CHANGE rappel_vaccin rappel_vaccin VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE centre_health CHANGE centre_city_id centre_city_id INT DEFAULT NULL, CHANGE centre_type_id centre_type_id INT DEFAULT NULL, CHANGE address_id address_id INT DEFAULT NULL, CHANGE city_id city_id INT DEFAULT NULL, CHANGE centre_referent centre_referent VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE telephone telephone INT DEFAULT NULL, CHANGE responsable_centre responsable_centre VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE num_rue num_rue VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE quartier quartier VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE city CHANGE region_id region_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE family CHANGE patient_child_id patient_child_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE group_family CHANGE designation designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE intervation_consultation CHANGE ordo_consulataion_id ordo_consulataion_id INT DEFAULT NULL, CHANGE intervation_medicale_id intervation_medicale_id INT DEFAULT NULL, CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE praticien_prescripteur_id praticien_prescripteur_id INT DEFAULT NULL, CHANGE praticien_consultant_id praticien_consultant_id INT DEFAULT NULL, CHANGE date_consultation date_consultation DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE intervation_medicale CHANGE praticien_id praticien_id INT DEFAULT NULL, CHANGE nature_intervation nature_intervation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE lieu_intervation lieu_intervation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE id_sante_patient id_sante_patient VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE intervention_vaccination CHANGE vaccin_id vaccin_id INT DEFAULT NULL, CHANGE praticien_prescripteur_id praticien_prescripteur_id INT DEFAULT NULL, CHANGE praticien_executant_id praticien_executant_id INT DEFAULT NULL, CHANGE intervation_medicale_id intervation_medicale_id INT DEFAULT NULL, CHANGE ordo_vaccination_id ordo_vaccination_id INT DEFAULT NULL, CHANGE status_vaccin status_vaccin VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE ordo_consultation CHANGE ordonnance_id ordonnance_id INT DEFAULT NULL, CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE reference_praticient_executant reference_praticient_executant VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE type_praticien type_praticien VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE ordo_medicaments CHANGE ordonnance_id ordonnance_id INT DEFAULT NULL, CHANGE patient_id patient_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ordo_vaccination DROP status_vaccin, CHANGE vaccin_id vaccin_id INT DEFAULT NULL, CHANGE ordonnance_id ordonnance_id INT DEFAULT NULL, CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE reference_praticien_executant_id reference_praticien_executant_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ordonnace CHANGE praticien_id praticien_id INT DEFAULT NULL, CHANGE medecin_traitant_id medecin_traitant_id INT DEFAULT NULL, CHANGE date_prescription date_prescription DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE patient CHANGE type_patient_id type_patient_id INT DEFAULT NULL, CHANGE address_id address_id INT DEFAULT NULL, CHANGE address_on_born_id address_on_born_id INT DEFAULT NULL, CHANGE last_name last_name VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE sexe sexe VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE father_name father_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE mother_name mother_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE etat etat TINYINT(1) DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE phone phone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE is_enceinte is_enceinte TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE patient_carnet_vaccination CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE carnet_vaccination_id carnet_vaccination_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patient_intervation_consultation CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE intervention_consultation_id intervention_consultation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patient_ordo_consultation CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE ordo_consultation_id ordo_consultation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patient_ordo_medicaments CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE ordo_medicaments_id ordo_medicaments_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patient_ordo_vaccination CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE ordo_vaccination_id ordo_vaccination_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patient_vaccin CHANGE patient_id patient_id INT DEFAULT NULL, CHANGE vaccin_id vaccin_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE praticien CHANGE user_id user_id INT DEFAULT NULL, CHANGE address_id address_id INT DEFAULT NULL, CHANGE last_name last_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE phone phone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE phone_professional phone_professional VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE etat etat TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE praticien_specialite CHANGE praticien_id praticien_id INT DEFAULT NULL, CHANGE specialite_id specialite_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE specialite CHANGE note_specialite note_specialite VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE user CHANGE email email VARCHAR(180) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE roles roles LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, CHANGE phone phone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE date_naissance date_naissance DATETIME DEFAULT \'NULL\', CHANGE lieu_naissance lieu_naissance VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE address address VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE activator_id activator_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE vaccin CHANGE type_vaccin_id type_vaccin_id INT DEFAULT NULL, CHANGE vaccin_description vaccin_description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE etat etat TINYINT(1) DEFAULT \'NULL\', CHANGE date_prise_initiale date_prise_initiale VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE rappel1 rappel1 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE rappel2 rappel2 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE rappel3 rappel3 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE rappel4 rappel4 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE rappel5 rappel5 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE rappel6 rappel6 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE rappel7 rappel7 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE rappel8 rappel8 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE rappel9 rappel9 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE rappel10 rappel10 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE vaccin_centre_health CHANGE centre_health_id centre_health_id INT DEFAULT NULL, CHANGE vaccin_id vaccin_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vaccin_praticien CHANGE praticien_id praticien_id INT DEFAULT NULL, CHANGE vaccin_id vaccin_id INT DEFAULT NULL');
    }
}
